### ISSUE TITLE
I'm not sure this compression is correct?

### ISSUE THREAD

**Issue by rieval** [kornelski/cavif-rs#62]
I tried processing several different images and the results showed that the compressed image size was not much smaller than the original size.

Version: [1.3.5](https://github.com/kornelski/cavif-rs/releases/tag/v1.3.5)

Command: `cavif.exe --speed=5 --overwrite image.jpg`

Original size: `9,331KB`
Compressed size: `8,571KB`

CPU: AMD Ryzen 5 PRO 4650U

**Comment by kornelski** [comment]
There are two factors here:

* When converting from an already-lossy format like JPEG you get worse quality/filesize ratio, because there's no magic that could restore quality that has already been lost, and the new format even wastes bits on preserving distortions added by the JPEG compression.
* 
* The speed setting unfortunately matters, and to get best file sizes you have to use slow modes.

**Comment by rieval** [comment]
Thanks!!
